### ISSUE TITLE
Program type already present error after adding dependancy

### ISSUE THREAD

**Issue by chimuu** [CleverTap/clevertap-segment-android-example#1]
I already had segment integrated in my app and now when I'm trying to integrate CleverTap, I'm not able to generate apk after adding clevertap dependancy

I'm using latest versions of gms and build-tools 

Here is the exact error
Error: Program type already present: com.google.firebase.iid.FirebaseInstanceId

Versions I'm using

```
  implementation 'com.clevertap.android:clevertap-segment-android:1.0.18'
  implementation 'com.segment.analytics.android:analytics:4.3.1'
  implementation 'com.google.firebase:firebase-messaging:17.3.4'
```

and 

```
  classpath 'com.android.tools.build:gradle:3.2.1'
  classpath 'com.google.gms:google-services:4.1.0'
```

**Comment by darshanclevertap** [comment]
@chimuu Sorry for the immense delay. Could you please update to the CleverTap Segment SDK v1.1.0 and update the `com.android.tools.build:gradle` to `3.3.1` and let us know if the issue still persists

**Comment by kumaratulme** [comment]
No further updates on this. Closing the issue.
